-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 09:58:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `ID` VARCHAR(36) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
;


-- -----------------------------------------------------
-- Table `TodoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TodoList` ;

CREATE TABLE IF NOT EXISTS `TodoList` (
  `ID` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TodoList_User_idx` (`UserId` ASC),
  CONSTRAINT `fk_TodoList_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `Todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Todo` ;

CREATE TABLE IF NOT EXISTS `Todo` (
  `ID` VARCHAR(36) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `TodoListId` VARCHAR(36) NOT NULL,
  `Status` VARCHAR(36) NOT NULL,
  `Deadline` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Todo_TodoList1_idx` (`TodoListId` ASC),
  CONSTRAINT `fk_Todo_TodoList1`
    FOREIGN KEY (`TodoListId`)
    REFERENCES `TodoList` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
